My fork
tattn/SwipeTransition pull request #46
Opened 2022-07-22 15:46 UTC by alexstich

2022-07-23 04:52 UTC, tattn requested changes
Thanks for the PR!

I'd like to merge these changes but would like to change the interface a bit.

2022-07-23 04:52 UTC, tattn commented on Sources/SwipeTransition/SwipeBack/SwipeBackController.swift
> +    }
If scrollView is nil, this method does nothing, so it is preferable not to use Optional at the argument.
```suggestion
    public func observeViewController(_ scrollView: UIScrollView, shouldBeginSwipe: @escaping () -> Bool) {
        scrollView.panGestureRecognizer.require(toFail: panGestureRecognizer)
        context.pageViewControllerGestureRecognizer = scrollView.panGestureRecognizer
        shouldBeginSwipeTransition = shouldBeginSwipe
    }
```

2022-07-23 04:52 UTC, tattn commented on Sources/SwipeTransition/SwipeBack/SwipeBackController.swift
> +        }
This is the same as the scrollView, too.
```suggestion
    public func observeViewController(view: UIView, shouldBeginSwipe: @escaping () -> Bool) {
        view.gestureRecognizers?.first?.require(toFail: panGestureRecognizer)
        context.pageViewControllerGestureRecognizer = view.gestureRecognizers?.first
        shouldBeginSwipeTransition = shouldBeginSwipe
```

2022-07-25 11:48 UTC, alexstich commented
I wanted to add an opportunity to add a few views in an array of excluded views that don't influence swipe transition. But couldn't do this. This pull request allows adding only one UIScrollView or UIView or UIPageViewController. It is not the best solution. But it help me a few times.

2022-07-25 18:54 UTC, tattn requested changes
This PR is great!
Finally, I'd like to make these changes for uniformity of method naming conventions.
And then I'll merge this PR.

2022-07-25 18:54 UTC, tattn commented on Sources/SwipeTransition/SwipeBack/SwipeBackController.swift
> +    public func observePageViewController(_ pageViewController: UIViewController, shouldBeginSwipe: @escaping (UIGestureRecognizer?) -> Bool) {
I want to change the name to "observe" to unify the naming convention.
```suggestion
    public func observe(viewController: UIViewController, shouldBeginSwipe: @escaping (UIGestureRecognizer) -> Bool) {
```

2022-07-25 18:54 UTC, tattn commented on Sources/SwipeTransition/SwipeBack/SwipeBackController.swift
> +    public func observeViewController(_ scrollView: UIScrollView, shouldBeginSwipe: @escaping (UIGestureRecognizer?) -> Bool) {
```suggestion
    public func observe(scrollView: UIScrollView, shouldBeginSwipe: @escaping (UIGestureRecognizer) -> Bool) {
```

2022-07-25 18:54 UTC, tattn commented on Sources/SwipeTransition/SwipeBack/SwipeBackController.swift
> +    public func observeViewController(view: UIView, shouldBeginSwipe: @escaping (UIGestureRecognizer?) -> Bool) {
```suggestion
    public func observe(view: UIView, shouldBeginSwipe: @escaping (UIGestureRecognizer) -> Bool) {
```

2022-07-25 18:54 UTC, tattn commented on Sources/SwipeTransition/SwipeBack/SwipeBackController.swift
> +    private var shouldBeginSwipeTransition: ((UIGestureRecognizer?) -> Bool)?
UIGestureRecognizer does not seem to need to be Optional.
```suggestion
    private var shouldBeginSwipeTransition: ((UIGestureRecognizer) -> Bool)?
```

2022-07-26 06:38 UTC, alexstich commented
After adding gesture to observer callback I use this method like this: 

`        self.vc?.navigationController?.swipeBack?.observe(view: observed_view, shouldBeginSwipe:
            { [weak self] gesture in
            
                guard let self = self else { return true }
            
                let frame_ = self.observed_view.frame
                let location = gesture.location(in: self.observed_view)
            
                if location.x < 0 || location.y < 0 || location.x > frame_.width || location.y > frame_.height {
                    return true
                }
            
                return false
            }
        )`

2022-07-27 12:41 UTC, tattn approved these changes
Thanks for the great improvements!

2022-07-27 12:42 UTC, merged